### ISSUE TITLE
Not an issue, only a request

### ISSUE THREAD

**Issue by filirnd** [itchyny/volume-go#13]
Hi, I like too much your lib. I want to use it for develop a little go program that mapping keyboards shortcut to system media controllers (play/pause, volume controller). There is a chance that you develop this commands (play/stop media) or there is another lib that you know and can to suggest to me?

Thank you in advance.

**Comment by itchyny** [comment]
Thank you. That sounds like an interesting idea, but volume-go isn't the right place for playing the media. I don't have motivation to create a lib for that feature. Maybe it's your idea and your chance to create a new library. I'm not sure it's possible to control media from terminal.

**Comment by filirnd** [comment]
Ok thank you for your answer. I close this "issue"
