### ISSUE TITLE
Ubuntu 18.04 Can't set volume/unmute

### ISSUE THREAD

**Issue by Programmerino** [itchyny/volume-go#2]
When using the following code, nothing happens and no errors are returned:
```go
err := volume.Unmute()
if err != nil {
	fmt.Println("Couldn't unmute volume!", err)
}
err = volume.SetVolume(100)
if err != nil {
	fmt.Println("Couldn't set volume!", err)
}
```
I am running the code on Ubuntu 18.04

**Comment by itchyny** [comment]
Thanks for feedback. Please confirm `pactl set-sink-mute 0 1` (mutes the audio) works or not.

**Comment by SkyrisBactera** [comment]
That command does not work. However, amixer commands to unmute, mute, etc. work fine.

**Comment by itchyny** [comment]
Sorry for being late, I supported amixer command.
